### ISSUE TITLE
contextMenuCtrl is undefined

### ISSUE THREAD

**Issue by tomy29** [ds82/angular-contextmenu#3] opened 2015-07-08 16:00 UTC
Hi,

I am trying to use your contextmenu directive.
I have an application with ui-router.
So I cannot run your example exactly like you do. 
In my routing file I am doing : 

```
angular.module('myApp')
    .config(function ($stateProvider) {
        $stateProvider
            .state('order', {
                parent: 'entity',
                url: '/order',
                views: {
                    'content@': {
                        templateUrl: 'path/order.html',
                        controller: 'orderController as ctrl'
                    }
                }....
```
Then I copy paste your code to my controller and HTML file, but I am getting an error : 
```
TypeError: undefined is not a function
    at http://localhost:8080/assets/js/directives/contextmenu.js:74:27
```
Seems like for my application contextMenuCtrl is undefined in the directive.

I know it's a bit hard to solve this without knowing the global context of my application but maybe you ll see what s wrong in my application.

Thanks in advance.

**Comment by ds82** [comment] 2015-07-09 10:41
Could you please post the HTML contextmenu code you use?

**Comment by tomy29** [comment] 2015-07-09 12:29
I have put your demo code in one of my html views : 

```
<div contextmenu="ctrl.contextmenu" class="dropdown contextmenu">
      <ul class="dropdown-menu" role="menu">
        <li class="dropdown-header">
          {{ ctrl.contextmenu.item.name }}
        </li>
        <li>
          <a role="menuitem" href 
            ng-click="ctrl.remove(ctrl.contextmenu.item)"
          >
            <span>Delete</span>
          </a>
        </li>
      </ul>
    </div>    

    <table class="table table-bordered table-striped" contextmenu-container="ctrl.contextmenu">
      <tr ng-repeat="row in data" contextmenu-item="row">
        <td>{{ row.id }}</td>
        <td>{{ row.name }}</td>
        <td>{{ row.email }}</td>
      </tr>
    </table>  
```

**Comment by ds82** [comment] 2015-07-09 14:03
hmm .. works for me with ui-router in this bin: http://jsbin.com/hodul/edit?html,js,output
Could you modify the bin to reproduce the error?

**Comment by tomy29** [comment] 2015-07-09 14:11
Actually I am using the framework Jhipster. All the structure of my application is done by this framework.
I don't have a ```<  body ng-controller="AppCtrl as ctrl">```

All my views go here ``` < div class="well" ui-view="content"></div>``` : 
```
<body ng-app="myApp">
        <!--[if lt IE 10]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
       <!--  <div ng-show="{{ENV === 'dev'}}" class="development" ng-cloak=""></div> -->
        <div class="container">
        	<div ui-view="navbar" ng-cloak=""></div>
        
            <div class="well" ui-view="content"></div>
        </div>
```

I guess the controllers are managed in a different way, that may causes the context menu not working.
If it's due to Jhipster architecture you may close this ticket.

**Comment by ds82** [comment] 2015-07-28 10:09
I spun up the jhipster docker image and tried to reproduce the error. Sadly for you, it works for me :/

![screen shot 2015-07-28 at 12 05 50](https://cloud.githubusercontent.com/assets/332905/8928836/5fb330d4-3521-11e5-885c-ad319746282b.png)

I'm closing the bug until you can provide an example where I can reproduce the error.

**Closed by ds82** 2015-07-28 10:09 UTC
